### ISSUE TITLE
HopScotch arrow blocks the link or input it is pointing to.

### ISSUE THREAD

**Issue by Davst** [linkedin/hopscotch#270]
If i point a tour item to a input field, the hidden part of the arrow div blocks clicks on that item. the only solution seems to be to have the arrow point at something else than where it should, or to offset the whole info box very far away
<img width="484" alt="hop-block" src="https://cloud.githubusercontent.com/assets/3330933/13847128/cd45be32-ec4b-11e5-9045-a7b9a4902780.png">

**Comment by DSnopov** [comment]
Hey @Davst . This should fix the issue: 
```css
.hopscotch-bubble-arrow-container {
  pointer-events: none;
}
```
